spring:
  application:
    name: user-api
  profiles:
    active: local
  elasticsearch:
    bboss:
      elasticPassword:
      elasticUser:
      elasticsearch:
        dateFormat: yyyy.MM.dd
        discoverHost: false
        rest:
          hostNames: 192.168.100.120:9200
        scrollBlockedWaitTimeout: 6000
        scrollThreadCount: 200
        scrollThreadQueue: 200
        showTemplate: true
        sliceScrollBlockedWaitTimeout: 6000
        sliceScrollThreadCount: 100
        sliceScrollThreadQueue: 100
        timeZone: Asia/Shanghai
      http:
        connectionRequestTimeout: 16000
        customHttpRequestRetryHandler: org.frameworkset.spi.remote.http.ConnectionResetHttpRequestRetryHandler
        defaultMaxPerRoute: 200
        evictExpiredConnections: false
        hostnameVerifier:
        keepAlive: 36000000
        keyPassword:
        keystore:
        maxHeaderCount: 200
        maxLineLength: -1
        maxTotal: 400
        retryTime: 1
        retryInterval: 1000
        soKeepAlive: false
        soReuseAddress: false
        staleConnectionCheckEnabled: false
        timeToLive: 36000
        timeoutConnection: 6000
        timeoutSocket: 6000
        validateAfterInactivity: 2000
      db:
        driver: com.mysql.jdbc.Driver
        name: test
        url: jdbc:mysql://localhost:3306/t_order
        usePool: false
        user: root
        password: 123456
        validateSQL: select 1
      dslfile:
        refreshInterval: -1


server:
  servlet:
    context-path: /user #设置项目ContextPath
  port: 8081 #设置Tomcat端口，默认8080
  tomcat:
    uri-encoding: UTF-8 #设置Tomcat编码